import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import { Header } from "../components/header";
import { useDarkModeStore } from "../context/darkmode";
import { Tasks } from "../screens/tasks/tasks";
import { darkTheme, lightTheme } from "../styles/theme";

const Home: NextPage = () => {
  const { theme } = useDarkModeStore();
  const themeMode = theme === "light" ? lightTheme : darkTheme;

  useEffect(() => {
    const classTheme = document.querySelector("#class-theme");
    if (!classTheme) return;
    classTheme.className = themeMode;
    return () => {}
  }, [themeMode]);

  return (
    <div id="class-theme">
      <Head>
        <title>Todo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="theme-color" content="#222222" />
      </Head>
      <Header />
      <Tasks />
    </div>
  );
};

export default Home;
